In [2]:
#importing numpy library
import numpy as np

In [3]:
arr = np.array([[1,3,3,6],
               [3,5,2,9]])
arr

array([[1, 3, 3, 6],
       [3, 5, 2, 9]])

In [5]:
#Array dimension
arr.ndim

2

In [6]:
arr.shape

(2, 4)

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.size

8

In [10]:
arr.data

In [12]:
arr.dtype

dtype('int32')

In [13]:
arr.itemsize

4

In [16]:
arr2 = np.array([[3,5,6,7],[5,3,2,5]], dtype=np.float64)
arr2

array([[3., 5., 6., 7.],
       [5., 3., 2., 5.]])

In [17]:
arr2.dtype

dtype('float64')

In [18]:
arr2.itemsize

8

In [27]:
z = np.array([[2,4,2,5],[4,5,3,2]], dtype=np.complex64)
t = np.array([[2,4,2,5],[4,5,3,2]], dtype=np.complex128)
print("For complex64: ", z)
print(z.dtype,"\n")
print(z.itemsize,"\n")
print("For complex128: ", t)
print(t.dtype,"\n")
print(t.itemsize,"\n")

For complex64:  [[2.+0.j 4.+0.j 2.+0.j 5.+0.j]
 [4.+0.j 5.+0.j 3.+0.j 2.+0.j]]
complex64 

8 

For complex128:  [[2.+0.j 4.+0.j 2.+0.j 5.+0.j]
 [4.+0.j 5.+0.j 3.+0.j 2.+0.j]]
complex128 

16 



In [28]:

arr3 = np.array([[1,3,3,6],
               [3,5,2,9]])


32


In [37]:
#sum
print(arr3,"\n")
print(np.sum(arr3))
print(np.sum(arr3, axis=0))
print(np.sum(arr3, axis=1))

[[1 3 3 6]
 [3 5 2 9]] 

32
[ 4  8  5 15]
[13 19]


In [38]:
#minimum value
print(arr3,"\n")
print(np.amin(arr3))
print(np.amin(arr3, axis=0))
print(np.amin(arr3, axis=1))

[[1 3 3 6]
 [3 5 2 9]] 

1
[1 3 2 6]
[1 2]


In [39]:
#maximum value
print(arr3,"\n")
print(np.amax(arr3))
print(np.amax(arr3, axis=0))
print(np.amax(arr3, axis=1))

[[1 3 3 6]
 [3 5 2 9]] 

9
[3 5 3 9]
[6 9]


In [40]:
#mean
print(arr3,"\n")
print("Mean: ", np.min(arr3))
print(np.mean(arr3, axis=0))
print(np.mean(arr3, axis=1))

[[1 3 3 6]
 [3 5 2 9]] 

Mean:  1
[2.  4.  2.5 7.5]
[3.25 4.75]


In [42]:
#median
print(arr3,"\n")
print("Median: ", np.median(arr3))
print(np.median(arr3, axis=0))
print(np.median(arr3, axis=1))

[[1 3 3 6]
 [3 5 2 9]] 

Median:  3.0
[2.  4.  2.5 7.5]
[3. 4.]


In [44]:
#Standard Deviation
print(arr3,"\n")
print("Standard Deviation: ", np.std(arr3))
print(np.std(arr3, axis=0))
print(np.std(arr3, axis=1))

[[1 3 3 6]
 [3 5 2 9]] 

Standard Deviation:  2.3979157616563596
[1.  1.  0.5 1.5]
[1.78535711 2.68095132]


In [45]:
#Variance
print(arr3,"\n")
print("Variance: ", np.var(arr3))
print(np.var(arr3, axis=0))
print(np.var(arr3, axis=1))

[[1 3 3 6]
 [3 5 2 9]] 

Variance:  5.75
[1.   1.   0.25 2.25]
[3.1875 7.1875]


In [47]:
#Weighted Average
print(np.average(arr3)) ## Average Without explicit weights

4.0


In [48]:
c = np.array([2,4,6,8,10,12,7,9,11])
print(c)

[ 2  4  6  8 10 12  7  9 11]


In [50]:
weight = np.array([0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25]) # Average with Weight
print(np.average(c, weights=weight))

7.846153846153846


In [53]:
#percentile
print(c,"\n")
print(np.percentile(c,5,0))
print(np.percentile(c,8,0))
print(np.percentile(arr3,5,1))

[ 2  4  6  8 10 12  7  9 11] 

2.8
3.2800000000000002
[1.3  2.15]


In [61]:
#peak to peak(MAX VALUE - MIN VALUE)
print(c)
print(np.ptp(c,0), "\n")

print(arr3)
print(np.ptp(arr3,0))
print(np.ptp(arr3,1))

[ 2  4  6  8 10 12  7  9 11]
10 

[[1 3 3 6]
 [3 5 2 9]]
[2 2 1 3]
[5 7]


In [67]:
#Reshape
arr4 = np.array([[1,2,3],[4,3,5],[5,3,2]])
print(arr3,"\n")
print(arr4.reshape(1,9), "\n")
print(arr3)

[[1 3 3 6]
 [3 5 2 9]] 

[[1 2 3 4 3 5 5 3 2]] 

[[1 3 3 6]
 [3 5 2 9]]


In [70]:
#Slicing 2D Array
l = np.array([[23,25,27,29],[43,45,47,49],[62,66,68,70]])
print(l,"\n")
print(l[0,3],"\n")
print(l[1,2],"\n")
print(l[2,3],"\n")
print(l[0,1],"\n")
print(l[0:2,1],"\n")
print(l[-1],"\n")
print(l[-1,0:2],"\n")

[[23 25 27 29]
 [43 45 47 49]
 [62 66 68 70]] 

29 

47 

70 

25 

[25 45] 

[62 66 68 70] 

[62 66] 



## Stacking

In [74]:
d = np.arange(12).reshape(3,4)
print(d,"\n")
f = np.arange(12,24).reshape(3,4)
print(f,"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 



In [76]:
print(d,"\n")
print(f,"\n")
print(np.hstack((d,f)),'\n')
print(np.hstack((f,d)),'\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]] 

[[12 13 14 15  0  1  2  3]
 [16 17 18 19  4  5  6  7]
 [20 21 22 23  8  9 10 11]] 



In [77]:
print(np.vstack((d,f)),'\n')
print(np.vstack((f,d)),'\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



## Random Number Generator using numpy

In [82]:
from numpy import random
x = random.rand()
print(x)

0.6875777367714818


In [83]:
from numpy import random
x = random.randint(100)
print(x)

94


In [85]:
# Generating random  array
x=random.randint(100,size=(5))
x

array([51, 82, 46, 95, 76])

In [86]:
x=random.randint(100,size=(5,10))
x

array([[22,  8,  8, 78, 41, 17, 84, 61, 65, 40],
       [67, 81, 78, 72, 12, 64,  6, 66, 76, 29],
       [43, 79, 11, 41, 68, 69, 79, 88, 18, 50],
       [82, 47, 89, 68, 17, 48, 21, 98, 19, 27],
       [64, 36,  0, 66, 35, 38, 23,  9, 13,  0]])